// Coachs Corbeil-Essonnes, transcrits depuis planning_cours_co.xlsx (juin 2024 - août 2025).
// Noms canonicalisés (casse harmonisée, variantes orthographiques évidentes fusionnées :
// 'max'->'Maxime', 'alycia'->'Alicia') — voir seedCorbeil.js pour le rattachement.
// NB : 'Enric' et 'Enrique' sont restés distincts (comptes conséquents chacun, pas une
// simple faute de frappe évidente) — a vérifier avec le manager si c'est bien la même personne.
module.exports = [
  "Abdel",
  "Adèle",
  "Alicia",
  "Andres",
  "Bastien",
  "Benoit",
  "Charlotte",
  "Cyril Alternant",
  "David",
  "Dimitri",
  "Elizabeth",
  "Enric",
  "Enrique",
  "Estelle",
  "Greg",
  "Halim",
  "Imane",
  "Julien",
  "Loic",
  "Louna",
  "Maelle",
  "Marc Matta",
  "Marvin",
  "Maxime",
  "Mokhtar",
  "Myriam",
  "Nacer",
  "Nasser",
  "Patrice",
  "Phillipe",
  "Renaud",
  "Robin",
  "Samia",
  "Selim",
  "Severine",
  "Vaiana",
  "Yamain",
];
