// Catalogue de cours par défaut, partagé entre le seed manuel (seed.js) et
// l'auto-remplissage au démarrage (seedDefaults.js) pour qu'une base vierge
// (nouvelle salle) soit immédiatement utilisable. Chaque salle peut ensuite
// ajouter/retirer des cours via l'API (POST /api/cours-types).
module.exports = [
  // Aqua
  { nom: 'Aquagym',              categorie: 'aqua' },
  { nom: 'Aquabike',             categorie: 'aqua' },
  { nom: 'Aquaboxing',           categorie: 'aqua' },
  { nom: 'Aquapower',            categorie: 'aqua' },
  { nom: 'Aquadynamique',        categorie: 'aqua' },
  { nom: 'Aquatraining',         categorie: 'aqua' },
  { nom: 'Aquapalming',          categorie: 'aqua' },
  { nom: 'Aquastep',             categorie: 'aqua' },
  { nom: 'Aquafusion',           categorie: 'aqua' },
  { nom: 'Aquatrampoline',       categorie: 'aqua' },
  { nom: 'Aquacircuit',          categorie: 'aqua' },
  // Fitness (bike)
  { nom: 'Biking',               categorie: 'fitness' },
  { nom: 'RPM',                  categorie: 'fitness' },
  // Fitness (salle)
  { nom: 'Bodybarre',            categorie: 'fitness' },
  { nom: 'CAF',                  categorie: 'fitness' },
  { nom: 'CAF XL',               categorie: 'fitness' },
  { nom: 'CAF 100% femmes',      categorie: 'fitness' },
  { nom: 'HIIT',                 categorie: 'fitness' },
  { nom: 'Bodypump',             categorie: 'fitness' },
  { nom: 'Bodycombat',           categorie: 'fitness' },
  { nom: "Fit'Combat",           categorie: 'fitness' },
  { nom: "Fit'Attack",           categorie: 'fitness' },
  { nom: 'Stretching postural',  categorie: 'fitness' },
  { nom: '100% stretching',      categorie: 'fitness' },
  { nom: '100% Abdos',           categorie: 'fitness' },
  { nom: 'Circuit training',     categorie: 'fitness' },
  { nom: 'K step',               categorie: 'fitness' },
  { nom: 'Crosstraining',        categorie: 'fitness' },
  { nom: 'Callisthénie',         categorie: 'fitness' },
  { nom: 'Step débutant',        categorie: 'fitness' },
  { nom: 'Step intermédiaire',   categorie: 'fitness' },
  { nom: 'Global training',      categorie: 'fitness' },
  { nom: 'Pilates',              categorie: 'fitness' },
  { nom: 'Zumba',                categorie: 'fitness' },
  { nom: 'Zumba 100% femmes',    categorie: 'fitness' },
  { nom: 'AfroDance',            categorie: 'fitness' },
  { nom: 'Boxe anglaise',        categorie: 'fitness' },
  { nom: 'Kick boxing 100% femmes', categorie: 'fitness' },
  { nom: 'SG 100% femmes',       categorie: 'fitness' },
  { nom: 'No Limit',             categorie: 'fitness' },
  { nom: 'Tabata XT',            categorie: 'fitness' },
  { nom: 'Lower Power',          categorie: 'fitness' },
  { nom: 'Upper Power',          categorie: 'fitness' },
  { nom: 'MMA Grappling',        categorie: 'fitness' },
  { nom: 'Pole dance',           categorie: 'fitness' },
  { nom: 'Forest Training',      categorie: 'fitness' },
  { nom: '100% Attack',          categorie: 'fitness' },
  { nom: 'Body Sculpt',          categorie: 'fitness' },
  { nom: 'Fit Dance',            categorie: 'fitness' },
  { nom: 'Gym douce',            categorie: 'fitness' },
  { nom: 'MMA Conf',             categorie: 'fitness' },
  { nom: 'MMA Deb',              categorie: 'fitness' },
  { nom: 'Sprint 30',            categorie: 'fitness' },
  { nom: 'Stretching',           categorie: 'fitness' },
  { nom: 'Yoga',                 categorie: 'fitness' },
  { nom: 'Initiation musculation', categorie: 'fitness' },
  { nom: 'Workout',              categorie: 'fitness' },
];
